Updating schedule

diff --git a/jobs/pipelines/daily-ocp4.7-powervs-tokyo-p9-min/Jenkinsfile b/jobs/pipelines/daily-ocp4.7-powervs-tokyo-p9-min/Jenkinsfile
--- a/jobs/pipelines/daily-ocp4.7-powervs-tokyo-p9-min/Jenkinsfile
+++ b/jobs/pipelines/daily-ocp4.7-powervs-tokyo-p9-min/Jenkinsfile
@@ -11,6 +11,7 @@ int FAILS_PER_THRESHOLD
 int UNSTALE_PER_THRESHOLD
 boolean INFRA_ISSUE = false
 env.BASTION_IP = ""
+boolean DEPLOYMENT_STATUS = false
 
 pipeline {
     agent {
@@ -60,7 +61,7 @@ pipeline {
         NUM_OF_WORKERS = "2"
 
         BASTION_IMAGE_NAME = "rhel-83-11242020"
-        RHCOS_IMAGE_NAME = "rhcos-45-09242020"
+        RHCOS_IMAGE_NAME = "rhcos-47-10172020"
 
         SYSTEM_TYPE = "s922"
         NETWORK_NAME = "ocp-net"
@@ -85,23 +86,20 @@ pipeline {
         UPGRADE_DELAY_TIME = ""
 
         TIMEOUT = "0"
-        OCP_RELEASE = "4.5"
+        OCP_RELEASE = "4.7"
 
         //e2e specific variables
         ENABLE_E2E_TEST = "true"
         E2E_GIT = "https://github.com/openshift/origin"
         E2E_BRANCH="release-${OCP_RELEASE}"
         E2E_EXCLUDE_LIST = "https://raw.github.ibm.com/redstack-power/e2e-exclude-list/${OCP_RELEASE}-powervm/ocp${OCP_RELEASE}_power_blacklist.txt"
-        GOLANG_TARBALL = "https://dl.google.com/go/go1.13.12.linux-ppc64le.tar.gz"
+        GOLANG_TARBALL = "https://golang.org/dl/go1.15.2.linux-ppc64le.tar.gz"
 
         //Makefile variables
         TERRAFORM_FORCE_KEYPAIR_CREATION = "0" //For not using build-barnes
-        OPENSHIFT_POWERVS_GIT_TF_DEPLOY_BRANCH="release-4.5" //The downlod branch
+        OPENSHIFT_POWERVS_GIT_TF_DEPLOY_BRANCH="master" //The downlod branch
 
-        //Script arguments
-        //ARTIFACTS_VERSION = "release-4.5"
-
-        TARGET = "deploy-openshift4-powervs-script"
+        TARGET = "deploy-openshift4-powervs"
         TERMPLATE_FILE = ".${TARGET}.tfvars.template"
 
         //To pick build-harness . Remove once the Makefile.openshift_pvc upstreamed
@@ -121,7 +119,7 @@ pipeline {
             steps {
                 script {
                     step([  $class: 'CopyArtifact',
-                    filter: 'latest-4.5-build.txt',
+                    filter: 'latest-4.7-build.txt',
                     fingerprintArtifacts: true,
                     projectName: 'mirror-openshift-release',
                     target: 'artifactory',
@@ -141,8 +139,8 @@ pipeline {
                     {
                         env.OPENSHIFT_IMAGE = ""
                         env.OCP_RELEASE_TAG = ""
-                        if (fileExists('artifactory/latest-4.5-build.txt')) {
-                            env.OPENSHIFT_IMAGE = readFile 'artifactory/latest-4.5-build.txt'
+                        if (fileExists('artifactory/latest-4.7-build.txt')) {
+                            env.OPENSHIFT_IMAGE = readFile 'artifactory/latest-4.7-build.txt'
                             env.OPENSHIFT_IMAGE = env.OPENSHIFT_IMAGE.trim()
                             env.OCP_RELEASE_TAG = env.OPENSHIFT_IMAGE.split(":")[1].trim()
                         }
@@ -150,23 +148,45 @@ pipeline {
                         if ("${env.OPENSHIFT_INSTALL_TARBALL}" == "null" )
                         {
                             echo "Unable to find openshift install tarball. falling back to default"
-                            env.OPENSHIFT_INSTALL_TARBALL="https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/4.5.5/openshift-install-linux.tar.gz"
+                            env.OPENSHIFT_INSTALL_TARBALL="https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp-dev-preview/4.6.0-0.nightly-ppc64le-2020-10-03-224643/openshift-install-linux.tar.gz"
                         }
                         env.OPENSHIFT_CLIENT_TARBALL=getOpenshiftClient(OCP_RELEASE)
                         if ("${env.OPENSHIFT_CLIENT_TARBALL}" == "null")
                         {
-                            env.OPENSHIFT_CLIENT_TARBALL="https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp/4.5.5/openshift-client-linux.tar.gz"
+                            env.OPENSHIFT_CLIENT_TARBALL="https://mirror.openshift.com/pub/openshift-v4/ppc64le/clients/ocp-dev-preview/4.6.0-0.nightly-ppc64le-2020-10-03-224643/openshift-client-linux.tar.gz"
                         }
                         env.OPENSHIFT_CLIENT_TARBALL_AMD64=getOpenshiftClientAMD(OCP_RELEASE)
                         if ("${env.OPENSHIFT_CLIENT_TARBALL_AMD64}" == "null")
                         {
-                            env.OPENSHIFT_CLIENT_TARBALL_AMD64="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.5.5/openshift-client-linux.tar.gz"
+                            env.OPENSHIFT_CLIENT_TARBALL_AMD64="https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/4.6.0-0.nightly-2020-10-03-051134/openshift-client-linux.tar.gz"
                         }
                     }
                     catch (err)
                     {
                         echo 'Error ! Template prepration failed !'
-                        getArtifactsAndCleanOcp4PvsScript(env.AUTH_URL)
+                        getArtifactsAndCleanOcp4(env.AUTH_URL)
+                        throw err
+                    }
+                }
+            }
+        }
+        stage('Setup terraform plugin') {
+            steps {
+                script {
+                    ansiColor('xterm') {
+                        echo ""
+                    }
+                    try {
+                        sh '''
+                        echo ' get the plugin from artifactory repo !'
+                        wget https://github.com/IBM-Cloud/terraform-provider-ibm/releases/download/v1.9.0/linux_amd64.zip
+                        mkdir -p ~/.terraform.d/plugins/linux_amd64/
+                        unzip linux_amd64.zip -d ~/.terraform.d/plugins/linux_amd64/
+                        '''
+                        }
+                    catch (err) {
+                        echo 'Error ! ENV setup failed!'
+                        getArtifactsAndCleanOcp4(env.AUTH_URL)
                         throw err
                     }
                 }
@@ -190,7 +210,7 @@ pipeline {
                         }
                     catch (err) {
                         echo 'Error ! ENV setup failed!'
-                        getArtifactsAndCleanOcp4PvsScript(env.AUTH_URL)
+                        getArtifactsAndCleanOcp4(env.AUTH_URL)
                         throw err
                     }
                 }
@@ -206,12 +226,23 @@ pipeline {
                         sh '''
                         echo 'Deploying Cluster!'
                         export TF_VAR_offline_remote_password=$TF_VAR_password
-                        export CLOUD_API_KEY=$IBMCLOUD_API_KEY
                         cd ${WORKSPACE}/deploy
-                        make $TARGET 
+                        make $TARGET || true
+                        retries=0
+                        until [ "$retries" -ge 3 ]
+                        do
+                                if [ "$retries" -eq 2 ]; then
+                                        make $TARGET:redeploy
+                                        sleep 60
+                                else
+                                        make $TARGET:redeploy || true
+                                fi
+                                retries=$((retries+1))
+                                sleep 10
+                        done
                         '''
-                        env.BASTION_IP=sh(returnStdout: true, script: "cd ${WORKSPACE}/deploy && make $TARGET:output TERRAFORM_OUTPUT_VAR=bastion_public_ip").trim()
-                        echo env.BASTION_IP
+                        env.BASTION_IP=sh(returnStdout: true, script: "cd ${WORKSPACE}/deploy && make terraform:output TERRAFORM_DIR=.${TARGET} TERRAFORM_OUTPUT_VAR=bastion_public_ip").trim()
+                        DEPLOYMENT_STATUS = true
                         }
                     catch (err) {
                         TIMEOUT_HRS =  WAIT_FOR_DEBUG.toInteger()
@@ -226,6 +257,30 @@ pipeline {
                 }
             }
         }
+
+        stage('Run crontab script for capturing outputs of multiple commands') {
+            steps {
+                script {
+                    ansiColor('xterm') {
+                        echo ""
+                    }
+                    try {
+                        sh '''
+                            cd ${WORKSPACE}/deploy
+                            scp -o 'StrictHostKeyChecking no' -i id_rsa ${WORKSPACE}/hack/cron.sh root@${BASTION_IP}:
+                            ssh -o 'StrictHostKeyChecking no' -i id_rsa root@${BASTION_IP} "chmod 755 cron.sh;
+                                                                                            echo '0 */2 * * * root ~/cron.sh >> ~/cron.log 2>&1' >> /etc/crontab;
+                                                                                            exit"
+                        '''
+                    } catch (err) {
+                        echo 'Running Crontab script failed!'
+                        getArtifactsAndCleanOcp4(env.AUTH_URL)
+                        throw err
+                    }
+                }
+            }
+        }
+
         stage('Setup and run ansible extra') {
             steps {
                 script {
@@ -264,7 +319,32 @@ pipeline {
                     }
                     catch (err) {
                         echo 'Error ! ENV setup failed!'
-                        getArtifactsAndCleanOcp4PvsScript(env.AUTH_URL)
+                        getArtifactsAndCleanOcp4(env.AUTH_URL)
+                        throw err
+                    }
+                }
+            }
+        }
+        stage('Setup Kubectl') {
+            steps {
+                script {
+                    ansiColor('xterm') {
+                        echo ""
+                    }
+                    try {
+                        setupKubeconfigOcp4()
+                        sh '''
+                        echo 'kubectl version'
+                        oc version
+                        echo 'Setting up kubectl!'
+                        oc get nodes
+                        echo 'Get the Cluster Operators'
+                        oc get co
+                        '''
+                        }
+                    catch (err) {
+                        echo 'Error ! Tearing off the cluster !'
+                        getArtifactsAndCleanOcp4(env.AUTH_URL)
                         throw err
                     }
                 }
@@ -278,14 +358,14 @@ pipeline {
                     }
                     try {
                         sh '''
-                           ssh -o 'StrictHostKeyChecking no' -i ${WORKSPACE}/deploy/id_rsa root@${BASTION_IP} "oc get --raw /debug/pprof/profile --as=system:admin" > cpu-pre.pprof || true
-                           ssh -o 'StrictHostKeyChecking no' -i ${WORKSPACE}/deploy/id_rsa root@${BASTION_IP} "oc get --raw /debug/pprof/heap --as=system:admin" > heap-pre.pprof || true
-                           ssh -o 'StrictHostKeyChecking no' -i ${WORKSPACE}/deploy/id_rsa root@${BASTION_IP} "oc --insecure-skip-tls-verify exec -n openshift-monitoring prometheus-k8s-0 -- tar cvzf - -C /prometheus . " > prometheus.tar.gz || true
+                           oc get --raw /debug/pprof/profile --as=system:admin > cpu-pre.pprof || true
+                           oc get --raw /debug/pprof/heap --as=system:admin > heap-pre.pprof || true
+                           oc --insecure-skip-tls-verify exec -n openshift-monitoring prometheus-k8s-0 -- tar cvzf - -C /prometheus . > prometheus.tar.gz || true
                         '''
                         }
                     catch (err) {
                         echo 'Error ! Tearing off the cluster !'
-                        getArtifactsAndCleanOcp4PvsScript(env.AUTH_URL)
+                        getArtifactsAndCleanOcp4(env.AUTH_URL)
                         throw err
                     }
                 }
@@ -294,14 +374,14 @@ pipeline {
     }
     post {
         always {
-            getArtifactsAndCleanOcp4PvsScript(env.AUTH_URL)
+            getArtifactsAndCleanOcp4(env.AUTH_URL)
             archiveArtifacts allowEmptyArchive: true, artifacts: 'deploy/conformance-parallel-out.txt.tar.gz', fingerprint: true, onlyIfSuccessful: false
             archiveArtifacts allowEmptyArchive: true, artifacts: 'deploy/summary.txt', fingerprint: true, onlyIfSuccessful: false
             archiveArtifacts allowEmptyArchive: true, artifacts: 'deploy/powervc.tfvars', fingerprint: true, onlyIfSuccessful: false
             archiveArtifacts allowEmptyArchive: true, artifacts: 'cpu-pre.pprof', fingerprint: true, onlyIfSuccessful: false
             archiveArtifacts allowEmptyArchive: true, artifacts: 'heap-pre.pprof', fingerprint: true, onlyIfSuccessful: false
             archiveArtifacts allowEmptyArchive: true, artifacts: 'prometheus.tar.gz', fingerprint: true, onlyIfSuccessful: false
-            archiveArtifacts allowEmptyArchive: true, artifacts: 'deploy/logs.tar.gz', fingerprint: true, onlyIfSuccessful: false
+            archiveArtifacts allowEmptyArchive: true, artifacts: 'deploy/cron.log', fingerprint: true, onlyIfSuccessful: false
             script {
                 if (fileExists('deploy/summary.txt')) {
                     E2E_SUMMARY = readFile 'deploy/summary.txt'
@@ -332,8 +412,10 @@ pipeline {
                    line1=line.toLowerCase()
                     if ( line1  != null) {
                         if (logContent_modified.contains(line1)){
-                            INFRA_ISSUE = true
-                            ERROR_MESSAGE = line1
+                            if ( ! DEPLOYMENT_STATUS ){
+                                INFRA_ISSUE = true
+                                ERROR_MESSAGE = line1
+                            }
                         }
                     }
                 }
